### ISSUE TITLE
game

### ISSUE THREAD

**Issue by Ziptiedmouse** [LDog44/Plat-Game#1]
this is trash

**Comment by Ziptiedmouse** [comment]
trash

**Comment by LDog44** [comment]
No u

**Comment by Ziptiedmouse** [comment]
y are you talking about yourself?

**Comment by LDog44** [comment]
I know you are but what am I?

**Comment by Ziptiedmouse** [comment]
youre mom

**Comment by LDog44** [comment]
*you're

**Comment by Ziptiedmouse** [comment]
LUKE AND SOME OTHER FEMALE COME TO THE FRONT OF THE CLASS TO CLEAN THE WHITEBOARD. the teacher said
ooooooooooooooooooooooooooooooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO, says every other soul in the class

**Comment by LDog44** [comment]
your granny tranny

**Comment by Ziptiedmouse** [comment]
no u
